# .coderabbit.yaml - Cấu hình review khắt khe
language: "vi"

reviews:
  enabled: true
  
  # Cấu hình tự động review
  auto_review:
    enabled: true
    threshold: "high"  # Chỉ review high và critical issues
    
  # Độ chi tiết review
  depth: "comprehensive"  # comprehensive, standard, concise
  
  # Phân tích chi tiết
  analysis:
    security: true
    performance: true
    best_practices: true
    code_smells: true
    complexity: true
    duplication: true
    maintainability: true
    
  # Tiêu chuẩn chất lượng nghiêm ngặt
  quality_gate:
    enabled: true
    rules:
      # Các rule chất lượng
      max_complexity: 10  # Độ phức tạp cyclomatic tối đa
      min_test_coverage: 80  # Tối thiểu 80% test coverage
      max_duplication: 5  # Tối đa 5% code trùng lặp
      max_smells: 20  # Tối đa 20 code smells
      min_maintainability: 60  # Điểm maintainability tối thiểu
    
  # Path filters - Review tất cả file source
  path_filters:
    - "src/**/*"
    - "lib/**/*"
    - "app/**/*"
    - "*.js"
    - "*.jsx"
    - "*.ts"
    - "*.tsx"
    - "*.py"
    - "*.java"
    - "*.cpp"
    - "*.c"
    - "*.go"
    - "*.rs"
    - "*.php"
    - "*.rb"
    - "*.swift"
    - "*.kt"
    - "!node_modules/**"
    - "!dist/**"
    - "!build/**"
    - "!*.min.js"
    - "!*.min.css"
    - "!vendor/**"
    - "!__pycache__/**"
  
  # File types cụ thể
  file_types:
    source_code: true
    configuration: true
    documentation: false  # Không review docs
    test_files: true  # Review cả test files
    
  # Cài đặt strict mode
  strict:
    enabled: true
    rules:
      # Bắt buộc các tiêu chuẩn
      require_comments: true  # Yêu cầu comment cho complex code
      require_tests: true  # Yêu cầu test cho new features
      no_debug_code: true  # Không cho phép debug code trong PR
      no_todo: true  # Cảnh báo TODO/FIXME comments
      no_hardcoded_secrets: true  # Check hardcoded secrets
      
  # Security scanning nâng cao
  security:
    enabled: true
    level: "strict"
    checks:
      - sql_injection
      - xss
      - csrf
      - path_traversal
      - command_injection
      - insecure_dependencies
      - secret_leakage
      
  # Performance analysis
  performance:
    enabled: true
    checks:
      - n_plus_one_queries
      - memory_leaks
      - inefficient_algorithms
      - large_file_size
      - too_many_imports
      
  # Chi tiết comments
  comments:
    style: "detailed"  # detailed, concise
    include_examples: true  # Bao gồm code examples
    include_fixes: true  # Gợi ý fix cụ thể
    maximum_comments: 50  # Giới hạn số comments
    
  # Pull request checks
  pull_request:
    require_all_checks: true  # Yêu cầu tất cả checks pass
    blocking_issues: true  # Có thể block PR nếu có critical issues
    minimum_approvals: 1  # Yêu cầu ít nhất 1 approval từ AI
    
  # Tự động request changes cho issues quan trọng
  auto_request_changes:
    enabled: true
    for_severities: ["critical", "high"]
  
chat:
  enabled: true
  strict_mode: true  # Mode nghiêm ngặt cho chat
